### ISSUE TITLE
production.rbの設定見直し+各環境の分け方や運用方法見直し→メールの動作確認必須→stagingにsettings.local.ymlを追加し、mailer>emailだけ追加する

### ISSUE THREAD

**Issue by hasebetakumi** [hasebetakumi/itto#222]
- [x]  backlogカラムからin progressカラムにチケット移動
- [x]  developブランチからブランチ切って開発開始
- [x]  単体テスト追加
- [x]  単体テスト
- [x]  プルリクもdevelopに対して行い。issueと連携させる
- [ ]  自動テストに合格後、developブランチにマージ

統合テストが必要なものは

- [ ]  test in sprint

不要なものは

- [x]  done in sprint

にチケット移動

**Comment by hasebetakumi** [comment]
readmeのメール認証の設定（gmailを用います）

でdb:create時に値が空だと怒られたと記載があるが、
local.setting.ymlの中でproduction用のurlを設定していないだけではないか？

現在production用の設定ファイルをgitignoreしているが、本来であればgit管理とするべき
現状だと変更を加えたい時にec2内で設定ファイルをいじらないといけない

→これはたぶんレプリカ環境が有るせいな気がする。
→development test production以外にレプリカ環境用の設定を入れないと、設定ファイルをgit管理内にはできない

**Comment by hasebetakumi** [comment]
上記対応で改善するかもしれないが、
メールの件名がパスになっている

**Comment by hasebetakumi** [comment]
gitignoreさせない
circleciも通す

**Comment by hasebetakumi** [comment]
```
# 本番環境で利用する定数
mailer:
    url: "https://system.itto-takasaka.com/"
    password: "rplbdibydemdihbf"
```
